### ISSUE TITLE
Dialogue for Scene 2, 3, and 4 does not get generated when you modify above fields

### ISSUE THREAD

**Issue by sungkim11** [deepmind/dramatron#4]
Modified Title, Characters, Scenes where there are more than 4, Settings where there are more than 4 to match Scenes, click on Scene 1, which generates a very light dialogue, but Scenes 2, 3, and 4 do not work.

**Comment by korymath** [comment]
Thank you for the note. We've made some bug fixes and this should be working now. 

Feel free to re-open and, if you are open share some screenshots, if it is still causing you trouble.

**Comment by sungkim11** [comment]
I am still encountering the same issues on the demo site. I am not able to re-open the issue since I am not a repo collaborator.
